seed: 17
device: "cuda:0"
output: "./output"

dataset:
  dataset: "NuscDataset"
  version: "mini"
  base_dir: /dataset/nuScenes/v1.0-mini
  image_dir: /dataset/nuScenes/nuScenes_clip
  road_gt_dir: /dataset/nuScenes/nuScenes_road_gt
  replace_name: False
  clip_list:
    - "scene-0655"

  min_distance: 0.2

  # resized image size
  image_width: 800
  image_height: 450

  camera_names:
    - "CAM_FRONT"
    - "CAM_FRONT_LEFT"
    - "CAM_FRONT_RIGHT"
    - "CAM_BACK"
    - "CAM_BACK_LEFT"
    - "CAM_BACK_RIGHT"

train:
  vis: False
  debug_from: -1
  detect_anomaly: False
  start_checkpoint: ""
  eval: True
  save: False

model:
  bev_resolution: 0.05 # meters
  cut_range: 8
  sh_degree: 3
  use_rgb: True
  opt_xy: False
  white_background: False
  use_exposure: True

optimization:
  epochs: 2
  random_background: False
  position_lr_init: 0.000016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 4000
  percent_dense: 0.01
  feature_lr: 0.0005
  opacity_lr: 0.0001
  scaling_lr: 0.0001
  rotation_lr: 0.0001
  rgb_lr: 0.008
  label_lr: 0.1
  exposure_lr: 0.001


  seg_loss_weight: 0.06
  smooth_loss_weight: 0.003  # 1 if z_weight > 0
  depth_loss_weight: 0
  z_weight: 0   # 0.02 if supervise z

pipeline:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False
